### ISSUE TITLE
Unable to encode/decode exi file 

### ISSUE THREAD

**Issue by Surekha95** [Martin-P/OpenV2G#1]
I'm getting issue as "Problems while decoding EXI stream, err==-110". I have used main_databinder functionality and attached zip contains input exi file. Please Can anyone assist me.
[1.zip](https://github.com/Martin-P/OpenV2G/files/5780673/1.zip)

**Comment by Martin-P** [comment]
Several years ago I imported it from the SourceForge for a project to have it preserved in case the original source code was removed. I did not write this code myself. 

It looks like an error code which is used only a few times in the source code. It is defined in [ OpenV2G/src/codec/ErrorCodes.h on line #60](https://github.com/Martin-P/OpenV2G/blob/bd9b7b13e49fda374cdaec428c8f22f3ca58edd2/src/codec/ErrorCodes.h#L60)
```c
#define EXI_ERROR_UNKOWN_EVENT_CODE -110
```
If you [search for `EXI_ERROR_UNKOWN_EVENT_CODE`](https://github.com/Martin-P/OpenV2G/search?q=EXI_ERROR_UNKOWN_EVENT_CODE) there are 4 matches. Perhaps this helps you to find the exact location which sets the `errn` variable?

I see there is a newer version of this code available at the original location: http://openv2g.sourceforge.net/

> OpenV2G 0.9.4 available
> 30 January 2018

If the problem is still there in OpenV2G 0.9.4 perhaps the author of the code can help. It looks like he still responds to issues which are created. See: https://sourceforge.net/p/openv2g/tickets/

I hope this helps you to find the cause of the problem.

**Comment by Surekha95** [comment]
> Several years ago I imported it from the SourceForge for a project to have it preserved in case the original source code was removed. I did not write this code myself.
> 
> It looks like an error code which is used only a few times in the source code. It is defined in [ OpenV2G/src/codec/ErrorCodes.h on line #60](https://github.com/Martin-P/OpenV2G/blob/bd9b7b13e49fda374cdaec428c8f22f3ca58edd2/src/codec/ErrorCodes.h#L60)
> 
> ```c
> #define EXI_ERROR_UNKOWN_EVENT_CODE -110
> ```
> 
> If you [search for `EXI_ERROR_UNKOWN_EVENT_CODE`](https://github.com/Martin-P/OpenV2G/search?q=EXI_ERROR_UNKOWN_EVENT_CODE) there are 4 matches. Perhaps this helps you to find the exact location which sets the `errn` variable?
> 
> I see there is a newer version of this code available at the original location: http://openv2g.sourceforge.net/
> 
> > OpenV2G 0.9.4 available
> > 30 January 2018
> 
> If the problem is still there in OpenV2G 0.9.4 perhaps the author of the code can help. It looks like he still responds to issues which are created. See: https://sourceforge.net/p/openv2g/tickets/
> 
> I hope this helps you to find the cause of the problem.

Thank you @Martin-P for the reply. I will do the same.
